const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
let pieces=[],fx=[],score=0,best=Number(localStorage.getItem('uhoBest')||0),gameOver=false,danger=0,nextLevel=0,aimX=180,canDrop=true,combo=0,comboTimer=0,maxLevel=0;
const sizes=[23,30,39,50,63,78,96],colors=['#d9954c','#ce823d','#bf7133','#ad612b','#9b5125','#87421f','#73351b'];
function resize(){const dpr=Math.min(devicePixelRatio||1,2),w=Math.min(innerWidth,430),h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);canvas.logicalWidth=w;canvas.logicalHeight=h;aimX=Math.min(aimX,w-32)}addEventListener('resize',resize);resize();
function pointerX(e){const r=canvas.getBoundingClientRect();return Math.max(30,Math.min(canvas.logicalWidth-30,e.clientX-r.left))}
canvas.addEventListener('pointermove',e=>{if(!gameOver)aimX=pointerX(e)});
canvas.addEventListener('pointerdown',e=>{if(gameOver){pieces=[];fx=[];score=0;danger=0;gameOver=false;nextLevel=0;combo=0;maxLevel=0;return}aimX=pointerX(e);if(!canDrop)return;const level=nextLevel,r=sizes[level];pieces.push({x:Math.max(r+8,Math.min(canvas.logicalWidth-r-8,aimX)),y:142,vx:0,vy:0,r,level});nextLevel=Math.random()<.72?0:1;canDrop=false;setTimeout(()=>canDrop=true,260)});
function burst(x,y,level){for(let i=0;i<12;i++){const a=Math.PI*2*i/12+Math.random()*.3,s=50+Math.random()*100;fx.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-30,life:.55,size:2+Math.random()*4,level})}}
function update(dt){comboTimer-=dt;if(comboTimer<=0)combo=0;const floor=canvas.logicalHeight-82;for(const p of pieces){p.vy+=1080*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.x-p.r<12){p.x=p.r+12;p.vx=Math.abs(p.vx)*.42}if(p.x+p.r>canvas.logicalWidth-12){p.x=canvas.logicalWidth-p.r-12;p.vx=-Math.abs(p.vx)*.42}if(p.y+p.r>floor){p.y=floor-p.r;p.vy=-Math.abs(p.vy)*.18;p.vx*=.93}}
for(let pass=0;pass<3;pass++)for(let i=0;i<pieces.length;i++)for(let j=i+1;j<pieces.length;j++){const a=pieces[i],b=pieces[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||.01,min=a.r+b.r;if(d>=min)continue;if(a.level===b.level&&a.level<sizes.length-1){const level=a.level+1,nx=(a.x+b.x)/2,ny=(a.y+b.y)/2;pieces.splice(j,1);pieces.splice(i,1,{x:nx,y:ny,vx:0,vy:-120,r:sizes[level],level});combo++;comboTimer=1.4;score+=(level+1)*10*combo;maxLevel=Math.max(maxLevel,level);burst(nx,ny,level);if(score>best){best=score;localStorage.setItem('uhoBest',best)}break}const nx=dx/d,ny=dy/d,o=min-d;a.x-=nx*o/2;a.y-=ny*o/2;b.x+=nx*o/2;b.y+=ny*o/2}
for(const f of fx){f.life-=dt;f.vy+=260*dt;f.x+=f.vx*dt;f.y+=f.vy*dt}fx=fx.filter(f=>f.life>0);const risky=pieces.some(p=>p.y-p.r<182&&Math.abs(p.vy)<35);danger=risky?danger+dt:Math.max(0,danger-dt*2);if(danger>1.8)gameOver=true}
function roundRect(x,y,w,h,r,fill){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill()}
function face(x,y,r,level,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.shadowColor='rgba(50,25,5,.25)';ctx.shadowBlur=Math.max(2,r*.12);ctx.shadowOffsetY=2;ctx.fillStyle=colors[level];ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.shadowColor='transparent';ctx.strokeStyle='#633816';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#efbc79';ctx.beginPath();ctx.ellipse(x,y+r*.12,r*.72,r*.57,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#20140d';ctx.beginPath();ctx.arc(x-r*.24,y-r*.14,Math.max(2,r*.07),0,Math.PI*2);ctx.arc(x+r*.24,y-r*.14,Math.max(2,r*.07),0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(x,y+r*.17,r*.22,0,Math.PI);ctx.stroke();if(level===6){ctx.font=`${Math.max(12,r*.28)}px sans-serif`;ctx.textAlign='center';ctx.fillText('★',x,y-r*.48)}ctx.restore()}
function background(w,h){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#9bc56c');g.addColorStop(.5,'#e7c77d');g.addColorStop(1,'#8cad58');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.14;for(let i=0;i<14;i++){ctx.fillStyle=i%2?'#245d2d':'#fff6b0';ctx.beginPath();ctx.ellipse((i*73)%w,(i*113)%h,40,14,i*.7,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
let previous=performance.now();function frame(now){const dt=Math.min((now-previous)/1000,.025);previous=now;if(!gameOver)update(dt);const w=canvas.logicalWidth,h=canvas.logicalHeight;background(w,h);
roundRect(10,10,w-20,88,16,'rgba(83,45,18,.88)');ctx.fillStyle='#ffe58a';ctx.font='900 22px -apple-system';ctx.fillText('ウホウホ パズル',22,39);ctx.fillStyle='#fff';ctx.font='700 15px -apple-system';ctx.fillText('SCORE '+score,22,65);ctx.fillStyle='#ffd966';ctx.fillText('BEST '+best,22,87);ctx.fillStyle='#fff';ctx.textAlign='right';ctx.font='700 12px -apple-system';ctx.fillText('NEXT',w-38,31);face(w-45,64,sizes[nextLevel]*.55,nextLevel);ctx.textAlign='left';
roundRect(10,106,w-20,h-180,18,'rgba(255,250,225,.34)');ctx.strokeStyle=danger>0?'#ef3b2d':'rgba(210,55,35,.7)';ctx.lineWidth=danger>0?4:2;ctx.setLineDash([9,7]);ctx.beginPath();ctx.moveTo(14,182);ctx.lineTo(w-14,182);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#8d241b';ctx.font='700 11px -apple-system';ctx.fillText('DANGER',18,176);ctx.strokeStyle='rgba(255,255,255,.75)';ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(aimX,100);ctx.lineTo(aimX,182);ctx.stroke();ctx.setLineDash([]);face(aimX,140,sizes[nextLevel],nextLevel,.62);pieces.forEach(p=>face(p.x,p.y,p.r,p.level));
for(const f of fx){ctx.globalAlpha=Math.max(0,f.life/.55);ctx.fillStyle=colors[f.level];ctx.beginPath();ctx.arc(f.x,f.y,f.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;if(combo>1&&comboTimer>0){ctx.fillStyle='#fff';ctx.strokeStyle='#7a3515';ctx.lineWidth=4;ctx.textAlign='center';ctx.font='900 30px -apple-system';ctx.strokeText('ウホッ! ×'+combo,w/2,235);ctx.fillText('ウホッ! ×'+combo,w/2,235);ctx.textAlign='left'}
roundRect(10,h-68,w-20,58,16,'rgba(83,45,18,.92)');for(let i=0;i<7;i++){const px=28+i*(w-56)/6;face(px,h-43,9+i*1.2,i,i<=maxLevel?1:.35);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='700 9px -apple-system';ctx.fillText('L'+(i+1),px,h-18)}ctx.textAlign='left';
if(gameOver){ctx.fillStyle='rgba(0,0,0,.7)';ctx.fillRect(0,0,w,h);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='900 35px -apple-system';ctx.fillText('GAME OVER',w/2,h/2-42);ctx.fillStyle='#ffe36e';ctx.font='800 23px -apple-system';ctx.fillText('SCORE '+score,w/2,h/2);ctx.fillStyle='#fff';ctx.font='17px -apple-system';ctx.fillText('タップでリトライ',w/2,h/2+48);ctx.textAlign='left'}requestAnimationFrame(frame)}requestAnimationFrame(frame);
