const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
let pieces=[],score=0,best=Number(localStorage.getItem('uhoBest')||0),gameOver=false,danger=0,nextLevel=0,aimX=180,canDrop=true;
const sizes=[24,32,42,54,68,84,102],colors=['#d58b43','#ca7b38','#bb6c30','#aa5c28','#984c22','#843d1d','#6f3018'];
function resize(){const dpr=Math.min(devicePixelRatio||1,2),w=Math.min(innerWidth,430),h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);canvas.logicalWidth=w;canvas.logicalHeight=h;aimX=Math.min(aimX,w-32)}addEventListener('resize',resize);resize();
function pointerX(e){const r=canvas.getBoundingClientRect();return Math.max(30,Math.min(canvas.logicalWidth-30,e.clientX-r.left))}
canvas.addEventListener('pointermove',e=>{if(!gameOver)aimX=pointerX(e)});
canvas.addEventListener('pointerdown',e=>{if(gameOver){pieces=[];score=0;danger=0;gameOver=false;nextLevel=0;return}aimX=pointerX(e);if(!canDrop)return;const level=nextLevel,r=sizes[level];pieces.push({x:Math.max(r+8,Math.min(canvas.logicalWidth-r-8,aimX)),y:105,vx:0,vy:0,r,level});nextLevel=Math.random()<.75?0:1;canDrop=false;setTimeout(()=>canDrop=true,280)});
function update(dt){const floor=canvas.logicalHeight-48;for(const p of pieces){p.vy+=1050*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.x-p.r<8){p.x=p.r+8;p.vx=Math.abs(p.vx)*.4}if(p.x+p.r>canvas.logicalWidth-8){p.x=canvas.logicalWidth-p.r-8;p.vx=-Math.abs(p.vx)*.4}if(p.y+p.r>floor){p.y=floor-p.r;p.vy=-Math.abs(p.vy)*.2;p.vx*=.94}}
for(let pass=0;pass<3;pass++)for(let i=0;i<pieces.length;i++)for(let j=i+1;j<pieces.length;j++){const a=pieces[i],b=pieces[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||.01,min=a.r+b.r;if(d>=min)continue;if(a.level===b.level&&a.level<sizes.length-1){const level=a.level+1;pieces.splice(j,1);pieces.splice(i,1,{x:(a.x+b.x)/2,y:(a.y+b.y)/2,vx:0,vy:-110,r:sizes[level],level});score+=(level+1)*10;if(score>best){best=score;localStorage.setItem('uhoBest',best)}break}const nx=dx/d,ny=dy/d,o=min-d;a.x-=nx*o/2;a.y-=ny*o/2;b.x+=nx*o/2;b.y+=ny*o/2}
const risky=pieces.some(p=>p.y-p.r<145&&Math.abs(p.vy)<35);danger=risky?danger+dt:Math.max(0,danger-dt*2);if(danger>1.8)gameOver=true}
function face(x,y,r,level,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.fillStyle=colors[level];ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#633816';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#efb56c';ctx.beginPath();ctx.ellipse(x,y+r*.12,r*.72,r*.55,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#20140d';ctx.beginPath();ctx.arc(x-r*.24,y-r*.13,Math.max(2,r*.07),0,Math.PI*2);ctx.arc(x+r*.24,y-r*.13,Math.max(2,r*.07),0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(x,y+r*.16,r*.22,0,Math.PI);ctx.stroke();ctx.restore()}
let previous=performance.now();function frame(now){const dt=Math.min((now-previous)/1000,.025);previous=now;if(!gameOver)update(dt);const w=canvas.logicalWidth,h=canvas.logicalHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='rgba(255,255,255,.62)';ctx.fillRect(10,10,w-20,70);ctx.fillStyle='#4b2c16';ctx.font='700 21px -apple-system';ctx.fillText('ウホウホパズル',20,36);ctx.font='700 16px -apple-system';ctx.fillText('SCORE '+score,20,62);ctx.textAlign='right';ctx.fillText('BEST '+best,w-20,62);ctx.textAlign='left';ctx.strokeStyle=danger>0?'#d22':'rgba(160,60,30,.5)';ctx.lineWidth=danger>0?3:2;ctx.setLineDash([8,8]);ctx.beginPath();ctx.moveTo(8,145);ctx.lineTo(w-8,145);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='rgba(90,50,20,.3)';ctx.beginPath();ctx.moveTo(aimX,82);ctx.lineTo(aimX,145);ctx.stroke();face(aimX,105,sizes[nextLevel],nextLevel,.42);pieces.forEach(p=>face(p.x,p.y,p.r,p.level));ctx.fillStyle='#80501f';ctx.fillRect(8,h-42,w-16,34);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='600 14px -apple-system';ctx.fillText('位置を決めてタップ　同じ顔で合体！',w/2,h-18);if(gameOver){ctx.fillStyle='rgba(0,0,0,.68)';ctx.fillRect(0,0,w,h);ctx.fillStyle='#fff';ctx.font='800 34px -apple-system';ctx.fillText('GAME OVER',w/2,h/2-35);ctx.font='700 22px -apple-system';ctx.fillText('SCORE '+score,w/2,h/2+2);ctx.font='17px -apple-system';ctx.fillText('タップでリトライ',w/2,h/2+45)}ctx.textAlign='left';requestAnimationFrame(frame)}requestAnimationFrame(frame);
