const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const monkeyFace=new Image();monkeyFace.src='assets/monkey-face.webp';
let pieces=[],fx=[],score=0,best=Number(localStorage.getItem('uhoBest')||0),state='title',danger=0,nextLevel=0,aimX=180,canDrop=true,combo=0,comboTimer=0,maxLevel=0;
const sizes=[23,30,39,50,63,78,96],colors=['#d9954c','#ce823d','#bf7133','#ad612b','#9b5125','#87421f','#73351b'];
function resize(){const dpr=Math.min(devicePixelRatio||1,2),w=Math.min(innerWidth,430),h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);canvas.logicalWidth=w;canvas.logicalHeight=h;aimX=Math.min(aimX,w-32)}addEventListener('resize',resize);resize();
function pointerX(e){const r=canvas.getBoundingClientRect();return Math.max(30,Math.min(canvas.logicalWidth-30,e.clientX-r.left))}
function reset(){pieces=[];fx=[];score=0;danger=0;nextLevel=0;combo=0;maxLevel=0;state='play'}
canvas.addEventListener('pointermove',e=>{if(state==='play')aimX=pointerX(e)});
canvas.addEventListener('pointerdown',e=>{const x=pointerX(e),y=e.clientY-canvas.getBoundingClientRect().top,w=canvas.logicalWidth,h=canvas.logicalHeight;if(state==='title'){if(y>h*.58&&y<h*.72)reset();return}if(state==='gameover'){if(y>h*.68){reset();return}}if(state==='paused'){if(y>h*.52&&y<h*.66)state='play';else if(y>h*.68)state='title';return}if(state!=='play')return;if(y<92&&x<72){state='paused';return}aimX=x;if(!canDrop)return;const level=nextLevel,r=sizes[level];pieces.push({x:Math.max(r+8,Math.min(w-r-8,aimX)),y:142,vx:0,vy:0,r,level});nextLevel=Math.random()<.72?0:1;canDrop=false;setTimeout(()=>canDrop=true,260)});
function burst(x,y,level){for(let i=0;i<16;i++){const a=Math.PI*2*i/16+Math.random()*.3,s=55+Math.random()*120;fx.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-40,life:.62,size:2+Math.random()*5,level})}}
function update(dt){comboTimer-=dt;if(comboTimer<=0)combo=0;const floor=canvas.logicalHeight-82;for(const p of pieces){p.vy+=1080*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.x-p.r<12){p.x=p.r+12;p.vx=Math.abs(p.vx)*.42}if(p.x+p.r>canvas.logicalWidth-12){p.x=canvas.logicalWidth-p.r-12;p.vx=-Math.abs(p.vx)*.42}if(p.y+p.r>floor){p.y=floor-p.r;p.vy=-Math.abs(p.vy)*.18;p.vx*=.93}}
for(let pass=0;pass<3;pass++)for(let i=0;i<pieces.length;i++)for(let j=i+1;j<pieces.length;j++){const a=pieces[i],b=pieces[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||.01,min=a.r+b.r;if(d>=min)continue;if(a.level===b.level&&a.level<sizes.length-1){const level=a.level+1,nx=(a.x+b.x)/2,ny=(a.y+b.y)/2;pieces.splice(j,1);pieces.splice(i,1,{x:nx,y:ny,vx:0,vy:-120,r:sizes[level],level});combo++;comboTimer=1.4;score+=(level+1)*10*combo;maxLevel=Math.max(maxLevel,level);burst(nx,ny,level);if(score>best){best=score;localStorage.setItem('uhoBest',best)}break}const ux=dx/d,uy=dy/d,o=min-d;a.x-=ux*o/2;a.y-=uy*o/2;b.x+=ux*o/2;b.y+=uy*o/2}
for(const f of fx){f.life-=dt;f.vy+=260*dt;f.x+=f.vx*dt;f.y+=f.vy*dt}fx=fx.filter(f=>f.life>0);const risky=pieces.some(p=>p.y-p.r<182&&Math.abs(p.vy)<35);danger=risky?danger+dt:Math.max(0,danger-dt*2);if(danger>1.8)state='gameover'}
function rr(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=3;ctx.stroke()}}
function face(x,y,r,level=0,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.shadowColor='rgba(50,25,5,.38)';ctx.shadowBlur=Math.max(3,r*.16);ctx.shadowOffsetY=3;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.clip();if(monkeyFace.complete&&monkeyFace.naturalWidth)ctx.drawImage(monkeyFace,x-r,y-r,r*2,r*2);else{ctx.fillStyle=colors[level];ctx.fillRect(x-r,y-r,r*2,r*2)}ctx.restore();ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle='#6b381c';ctx.lineWidth=Math.max(1.5,r*.045);ctx.beginPath();ctx.arc(x,y,r-1,0,Math.PI*2);ctx.stroke();if(level===6){ctx.textAlign='center';ctx.font=`${Math.max(15,r*.34)}px sans-serif`;ctx.fillText('👑',x,y-r*.72)}ctx.restore()}
function background(w,h){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#b9d98a');g.addColorStop(.48,'#f1d597');g.addColorStop(1,'#91b55d');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.13;for(let i=0;i<16;i++){ctx.fillStyle=i%2?'#245d2d':'#fff6b0';ctx.beginPath();ctx.ellipse((i*73)%w,(i*113)%h,42,15,i*.7,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function button(x,y,w,h,label,primary=true){rr(x,y,w,h,h/2,primary?'#ffc83d':'#fff8e9','#713b1d');ctx.fillStyle='#4b2816';ctx.textAlign='center';ctx.font='900 20px -apple-system';ctx.fillText(label,x+w/2,y+h*.64);ctx.textAlign='left'}
function titleScreen(w,h){background(w,h);ctx.textAlign='center';ctx.strokeStyle='#6e3518';ctx.lineWidth=7;ctx.fillStyle='#ffcf3f';ctx.font='900 38px -apple-system';ctx.strokeText('ウホッ！',w/2,70);ctx.fillText('ウホッ！',w/2,70);ctx.font='900 35px -apple-system';ctx.strokeText('モンキーパズル',w/2,111);ctx.fillText('モンキーパズル',w/2,111);ctx.fillStyle='#5d331c';ctx.font='800 12px -apple-system';ctx.fillText('UHO! MONKEY PUZZLE',w/2,133);face(w/2,h*.39,Math.min(112,w*.28),0);rr(w*.19,h*.49,w*.62,58,22,'#fff9e8','#70401f');ctx.fillStyle='#5b321d';ctx.font='800 16px -apple-system';ctx.fillText('同じ顔をくっつけて',w/2,h*.49+24);ctx.fillText('どんどん大きくしよう！',w/2,h*.49+46);button(w*.13,h*.59,w*.74,62,'ゲームスタート');button(w*.2,h*.70,w*.6,52,'あそびかた',false);ctx.fillStyle='#70401f';ctx.font='700 13px -apple-system';ctx.fillText('BEST SCORE  '+best,w/2,h*.83);ctx.textAlign='left'}
function playScreen(w,h){background(w,h);rr(10,10,w-20,88,16,'rgba(83,45,18,.9)');rr(18,21,44,44,10,'#c9823d','#6a371c');ctx.fillStyle='#fff';ctx.font='900 22px sans-serif';ctx.fillText('Ⅱ',30,51);ctx.fillStyle='#ffe58a';ctx.font='900 19px -apple-system';ctx.fillText('ウホッ！モンキーパズル',72,38);ctx.fillStyle='#fff';ctx.font='700 14px -apple-system';ctx.fillText('SCORE '+score,72,62);ctx.fillStyle='#ffd966';ctx.fillText('BEST '+best,72,84);ctx.fillStyle='#fff';ctx.textAlign='right';ctx.font='700 11px -apple-system';ctx.fillText('ネクスト',w-31,29);face(w-45,63,sizes[nextLevel]*.55,nextLevel);ctx.textAlign='left';rr(10,106,w-20,h-180,18,'rgba(255,250,225,.38)','rgba(255,255,255,.65)');ctx.strokeStyle=danger>0?'#ef3b2d':'rgba(210,55,35,.72)';ctx.lineWidth=danger>0?4:2;ctx.setLineDash([9,7]);ctx.beginPath();ctx.moveTo(14,182);ctx.lineTo(w-14,182);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#8d241b';ctx.font='700 11px -apple-system';ctx.fillText('ゲームオーバーライン',18,176);ctx.strokeStyle='rgba(255,255,255,.8)';ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(aimX,100);ctx.lineTo(aimX,182);ctx.stroke();ctx.setLineDash([]);face(aimX,140,sizes[nextLevel],nextLevel,.72);pieces.forEach(p=>face(p.x,p.y,p.r,p.level));for(const f of fx){ctx.globalAlpha=Math.max(0,f.life/.62);ctx.fillStyle=colors[f.level];ctx.beginPath();ctx.arc(f.x,f.y,f.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;if(combo>1&&comboTimer>0){ctx.fillStyle='#fff';ctx.strokeStyle='#7a3515';ctx.lineWidth=5;ctx.textAlign='center';ctx.font='900 31px -apple-system';ctx.strokeText('ウホー!! ×'+combo,w/2,238);ctx.fillText('ウホー!! ×'+combo,w/2,238);ctx.textAlign='left'}rr(10,h-68,w-20,58,16,'rgba(83,45,18,.94)');for(let i=0;i<7;i++){const px=28+i*(w-56)/6;face(px,h-43,9+i*1.2,i,i<=maxLevel?1:.35);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='700 9px -apple-system';ctx.fillText('Lv'+(i+1),px,h-18)}ctx.textAlign='left'}
function overlay(w,h){ctx.fillStyle='rgba(20,15,10,.76)';ctx.fillRect(0,0,w,h);ctx.textAlign='center';if(state==='paused'){rr(w*.12,h*.25,w*.76,h*.48,24,'#6b371d','#e5aa5a');ctx.fillStyle='#fff';ctx.font='900 34px -apple-system';ctx.fillText('ポーズ',w/2,h*.34);button(w*.2,h*.52,w*.6,58,'ゲームにもどる');button(w*.2,h*.66,w*.6,52,'タイトルにもどる',false)}else{rr(w*.09,h*.16,w*.82,h*.69,25,'#542b19','#d79245');ctx.fillStyle='#fff';ctx.font='900 35px -apple-system';ctx.fillText('ゲームオーバー',w/2,h*.25);face(w/2,h*.39,64,0);ctx.fillStyle='#fff';ctx.font='700 16px -apple-system';ctx.fillText('今回のスコア',w/2,h*.52);ctx.font='900 32px -apple-system';ctx.fillText(score.toLocaleString(),w/2,h*.57);ctx.fillStyle='#ffd96b';ctx.font='800 17px -apple-system';ctx.fillText('ベストスコア  '+best.toLocaleString(),w/2,h*.62);button(w*.16,h*.68,w*.68,58,'リトライ');ctx.fillStyle='#fff';ctx.font='14px -apple-system';ctx.fillText('また遊んでね…ウホ',w/2,h*.81)}ctx.textAlign='left'}
let previous=performance.now();function frame(now){const dt=Math.min((now-previous)/1000,.025);previous=now;const w=canvas.logicalWidth,h=canvas.logicalHeight;if(state==='play')update(dt);if(state==='title')titleScreen(w,h);else{playScreen(w,h);if(state==='paused'||state==='gameover')overlay(w,h)}requestAnimationFrame(frame)}requestAnimationFrame(frame);
